name: Swift Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    timeout-minutes: 60
    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3    

    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"

    - name: Run tests
      run: swift test --parallel
