name: Swift Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [[swift-latest, ubuntu-latest, self-hosted], [swift-nightly, ubuntu-latest, self-hosted]]

    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3    

    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build

    - name: Run tests
      run: |
        [ -d Tests ] && swift test --parallel
