name: Swift Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3    
    - name: Run tests
      run: swift test --parallel
