name: Swift code coverage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-code-coverage:
    runs-on: [self-hosted, ubuntu-latest]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"
    - name: Run tests
      run: swift test --parallel --enable-code-coverage
#    - name: Extract default SPM library testtarget
#      id: spm_test_target
#      run: |
#        SPM_DEFAULT_TEST_TARGET=$(swift package dump-package | jq -r '.targets | .[] | select(.type == "test") | .name' | tail -1)
#        echo "::set-output name=spmlibrarytesttarget::$SPM_DEFAULT_TEST_ARGET"
    - name: Export code coverage
      run: llvm-cov export -format="lcov" .build/debug/${{ github.event.repository.name }}PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload codecov
      uses: codecov/codecov-action@v2
      with: 
        token: ${{ secrets.CODECOV_REPO_TOKEN }} 
        files: info.lcov
