name: Swift address sanitizer macOS
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  address-sanitizer-macos:
    timeout-minutes: 30
    runs-on: [self-hosted, macos-12]
    steps:
      - name: Wipe gitconfig
        run: echo "" > ~/.gitconfig
      - uses: actions/checkout@v3
      - name: Git URL token override
        run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"
      - name: Clean before debug build address sanitizier
        run: swift package clean
      - name: Run address sanitizer
        run: swift test --sanitize=address
      - name: Clean before release build address sanitizier
        run: swift package clean
      - name: Run address sanitizer on release build
        run: swift test --sanitize=address -c release -Xswiftc -enable-testing | swift demangle
      - name: Wipe gitconfig
        run: echo "" > ~/.gitconfig
